name: "Gated Apply - Raise an issue"

permissions:
  issues: write

on:
  workflow_dispatch:
    inputs:
      dev_deploy:
        description: Enable deployment to development environment
        required: true
        default: true
        type: boolean
      action:
        description: Select Terraform action to run.
        type: choice
        required: true
        options:
        - plan
        - apply
      components:
        description: Provide terraform component list to deploy to environment.
        required: true
        type: string
        default: '["account"]'
      terraform_args:
        description: Additional arguments to pass to terraform
        required: false
        type: string
        default: ''

jobs:
  tf_gated_apply:
    name: "Terraform Gated Apply"
    runs-on: ubuntu-latest
    steps:

      # Terraform plan
      - name: "Terraform plan"
        run: echo "Planning the terraform code here..."

      # Raise an issue to approve the apply
      - name: Raising issue for approval
        uses: trstringer/manual-approval@v1
        with:
          #          secret: ${{ github.TOKEN }}
          approvers: drathbone
          minimum-approvals: 1
          issue-title: "Approval to run Terraform apply"
          issue-body: "Please approve or deny the terraform apply"

      # Terraform apply
      - name: "Terraform apply"
        run: echo "Applying the terraform code here..."

