name: "Gated Apply - Env Protection one"

permissions:
  issues: write

on:
  workflow_dispatch:
    inputs:
      dev_deploy:
        description: Enable deployment to development environment
        required: true
        default: true
        type: boolean
      action:
        description: Select Terraform action to run.
        type: choice
        required: true
        options:
        - plan
        - apply
      components:
        description: Provide terraform component list to deploy to environment.
        required: true
        type: string
        default: '["account"]'
      terraform_args:
        description: Additional arguments to pass to terraform
        required: false
        type: string
        default: ''

jobs:
  tf_plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    environment: "prod"
    steps:
      # Terraform plan (unprotected environment)
      - name: "Terraform plan"
        run: echo "Planning the terraform code here..."

  approval:
    name: "Approval for apply"
    needs: [tf_plan]
    runs-on: ubuntu-latest
    environment: "gated-approval"
    steps:
      - name: "Approval required to apply terraform"
        run: echo "Approval for apply has been granted"

  tf_apply:
    name: "Terraform Apply"
    needs: [approval]
    runs-on: ubuntu-latest
    environment: "prod"
    steps:
      # Terraform apply
      - name: "Terraform apply"
        run: echo "Applying the terraform code here..."

